#!/usr/bin/env node

/**
 * Vocabulary Sync Backend Deployment Script
 *
 * This script:
 * 1. Prompts for AWS region and stack configuration (or loads from .env.deploy)
 * 2. Saves configuration to .env.deploy for persistence
 * 3. Generates samconfig.toml
 * 4. Runs sam build and sam deploy
 * 5. Captures stack outputs (API Gateway URL)
 * 6. Updates .env file automatically with EXPO_PUBLIC_SYNC_API_URL
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

// eslint-disable-next-line no-undef
const PROJECT_ROOT = path.join(__dirname, '..');
const BACKEND_DIR = path.join(PROJECT_ROOT, 'backend');
const ENV_DEPLOY_PATH = path.join(BACKEND_DIR, '.env.deploy');
const ENV_PATH = path.join(PROJECT_ROOT, '.env');
const SAMCONFIG_PATH = path.join(BACKEND_DIR, 'samconfig.toml');

// Create readline interface for user input
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

// Utility to ask a question
function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, resolve);
  });
}

// Load existing .env.deploy if it exists
function loadEnvDeploy() {
  const config = {};

  if (fs.existsSync(ENV_DEPLOY_PATH)) {
    console.log('Loading configuration from .env.deploy...\n');
    const content = fs.readFileSync(ENV_DEPLOY_PATH, 'utf8');

    content.split('\n').forEach(line => {
      line = line.trim();
      if (line && !line.startsWith('#')) {
        const [key, ...valueParts] = line.split('=');
        const value = valueParts.join('=').trim();
        config[key.trim()] = value;
      }
    });
  }

  return config;
}

// Save configuration to .env.deploy
function saveEnvDeploy(config) {
  const content = `# Vocabulary Sync Backend Deployment Configuration
# This file is auto-generated by the deploy script

# Stack Name (used for CloudFormation stack and S3 bucket naming)
STACK_NAME=${config.STACK_NAME}

# AWS Region
AWS_REGION=${config.AWS_REGION}

# Include Dev Origins (allows all origins for local development)
INCLUDE_DEV_ORIGINS=${config.INCLUDE_DEV_ORIGINS}

# Production Origins (comma-separated list of allowed origins for CORS)
# Example: https://vocabulary.example.com,https://www.vocabulary.example.com
PRODUCTION_ORIGINS=${config.PRODUCTION_ORIGINS}

# Lambda Configuration
LAMBDA_MEMORY=${config.LAMBDA_MEMORY}
LAMBDA_TIMEOUT=${config.LAMBDA_TIMEOUT}
`;

  fs.writeFileSync(ENV_DEPLOY_PATH, content);
  console.log('✓ Configuration saved to backend/.env.deploy\n');
}

// Generate samconfig.toml (secrets passed at deploy time via CLI)
function generateSamConfig(config) {
  const deployBucket = `sam-deploy-${config.STACK_NAME}-${config.AWS_REGION}`;

  const samconfig = `version = 0.1

[default]
[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
stack_name = "${config.STACK_NAME}"
s3_bucket = "${deployBucket}"
s3_prefix = "${config.STACK_NAME}"
region = "${config.AWS_REGION}"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
`;

  fs.writeFileSync(SAMCONFIG_PATH, samconfig);
  console.log('✓ Generated backend/samconfig.toml\n');
}

// Update .env file with API Gateway URL
function updateEnvFile(apiUrl) {
  let envContent = '';

  // Read existing .env if it exists
  if (fs.existsSync(ENV_PATH)) {
    envContent = fs.readFileSync(ENV_PATH, 'utf8');
  }

  // Update or add EXPO_PUBLIC_SYNC_API_URL
  const apiUrlPattern = /^EXPO_PUBLIC_SYNC_API_URL=.*/m;

  if (apiUrlPattern.test(envContent)) {
    envContent = envContent.replace(apiUrlPattern, `EXPO_PUBLIC_SYNC_API_URL=${apiUrl}`);
  } else {
    envContent = envContent.trim();
    if (envContent) {
      envContent += '\n';
    }
    envContent += `EXPO_PUBLIC_SYNC_API_URL=${apiUrl}\n`;
  }

  fs.writeFileSync(ENV_PATH, envContent);
  console.log(`✓ Updated .env with EXPO_PUBLIC_SYNC_API_URL=${apiUrl}\n`);
}

// Execute shell command and stream output
function execCommand(command, cwd = BACKEND_DIR) {
  console.log(`> ${command}\n`);

  try {
    execSync(command, {
      cwd,
      stdio: 'inherit',
      env: process.env
    });
  } catch (error) {
    console.error(`\n✗ Command failed: ${command}`);
    process.exit(1);
  }
}

// Get CloudFormation stack outputs
function getStackOutputs(stackName, region) {
  try {
    const command = `aws cloudformation describe-stacks --stack-name ${stackName} --region ${region} --query 'Stacks[0].Outputs' --output json`;
    const output = execSync(command, { encoding: 'utf8' });
    return JSON.parse(output);
  } catch (error) {
    console.error('✗ Failed to get stack outputs');
    throw error;
  }
}

// Check prerequisites
function checkPrerequisites() {
  console.log('Checking prerequisites...\n');

  // Check AWS CLI
  try {
    execSync('aws sts get-caller-identity', { stdio: 'pipe' });
    console.log('✓ AWS CLI configured');
  } catch {
    console.error('✗ AWS CLI not configured. Run: aws configure');
    process.exit(1);
  }

  // Check SAM CLI
  try {
    execSync('sam --version', { stdio: 'pipe' });
    console.log('✓ SAM CLI installed\n');
  } catch {
    console.error('✗ SAM CLI not installed.');
    console.error('  Visit: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html');
    process.exit(1);
  }
}

// Main deployment flow
async function deploy() {
  console.log('==========================================');
  console.log('Vocabulary Sync Backend Deployment');
  console.log('==========================================\n');

  checkPrerequisites();

  // Load existing configuration
  const config = loadEnvDeploy();

  // Set defaults for missing values
  const defaults = {
    STACK_NAME: config.STACK_NAME || 'vocabulary-sync',
    AWS_REGION: config.AWS_REGION || 'us-west-2',
    INCLUDE_DEV_ORIGINS: config.INCLUDE_DEV_ORIGINS || 'true',
    PRODUCTION_ORIGINS: config.PRODUCTION_ORIGINS || '',
    LAMBDA_MEMORY: config.LAMBDA_MEMORY || '256',
    LAMBDA_TIMEOUT: config.LAMBDA_TIMEOUT || '10',
  };

  console.log('Press Enter to use defaults shown in brackets.\n');

  // Prompt for stack name
  const stackNameInput = await ask(`Stack Name [${defaults.STACK_NAME}]: `);
  config.STACK_NAME = stackNameInput.trim() || defaults.STACK_NAME;

  // Validate stack name format
  if (!/^[a-z][a-z0-9-]*$/.test(config.STACK_NAME)) {
    console.error('✗ Stack name must start with lowercase letter and contain only lowercase letters, numbers, and hyphens');
    rl.close();
    process.exit(1);
  }

  // Prompt for AWS region
  const regionInput = await ask(`AWS Region [${defaults.AWS_REGION}]: `);
  config.AWS_REGION = regionInput.trim() || defaults.AWS_REGION;

  // Prompt for dev origins (allows * for local development)
  const devOriginsInput = await ask(`Include Dev Origins - allows all origins (true/false) [${defaults.INCLUDE_DEV_ORIGINS}]: `);
  config.INCLUDE_DEV_ORIGINS = devOriginsInput.trim() || defaults.INCLUDE_DEV_ORIGINS;

  // Validate dev origins
  if (!['true', 'false'].includes(config.INCLUDE_DEV_ORIGINS)) {
    console.error('✗ Include Dev Origins must be "true" or "false"');
    rl.close();
    process.exit(1);
  }

  // Prompt for production origins
  const prodOriginsDisplay = defaults.PRODUCTION_ORIGINS || '(none)';
  console.log('\nProduction Origins: Comma-separated list of allowed origins for CORS');
  console.log('Example: https://vocabulary.example.com,https://www.vocabulary.example.com');
  const prodOriginsInput = await ask(`Production Origins [${prodOriginsDisplay}]: `);
  config.PRODUCTION_ORIGINS = prodOriginsInput.trim() || defaults.PRODUCTION_ORIGINS;

  // Prompt for Lambda memory
  const memoryInput = await ask(`Lambda Memory MB (128-10240) [${defaults.LAMBDA_MEMORY}]: `);
  config.LAMBDA_MEMORY = memoryInput.trim() || defaults.LAMBDA_MEMORY;

  // Validate memory
  const memoryNum = parseInt(config.LAMBDA_MEMORY, 10);
  if (isNaN(memoryNum) || memoryNum < 128 || memoryNum > 10240) {
    console.error('✗ Lambda memory must be between 128 and 10240 MB');
    rl.close();
    process.exit(1);
  }

  // Prompt for Lambda timeout
  const timeoutInput = await ask(`Lambda Timeout seconds (1-900) [${defaults.LAMBDA_TIMEOUT}]: `);
  config.LAMBDA_TIMEOUT = timeoutInput.trim() || defaults.LAMBDA_TIMEOUT;

  // Validate timeout
  const timeoutNum = parseInt(config.LAMBDA_TIMEOUT, 10);
  if (isNaN(timeoutNum) || timeoutNum < 1 || timeoutNum > 900) {
    console.error('✗ Lambda timeout must be between 1 and 900 seconds');
    rl.close();
    process.exit(1);
  }

  rl.close();

  // Display configuration
  console.log('\n--- Configuration ---');
  console.log(`  Stack Name:         ${config.STACK_NAME}`);
  console.log(`  AWS Region:         ${config.AWS_REGION}`);
  console.log(`  Include Dev Origins: ${config.INCLUDE_DEV_ORIGINS}`);
  console.log(`  Production Origins:  ${config.PRODUCTION_ORIGINS || '(none)'}`);
  console.log(`  Lambda Memory:       ${config.LAMBDA_MEMORY} MB`);
  console.log(`  Lambda Timeout:      ${config.LAMBDA_TIMEOUT} seconds`);
  console.log('---------------------\n');

  // Save configuration
  saveEnvDeploy(config);
  generateSamConfig(config);

  // Create S3 deployment bucket if needed
  const deployBucket = `sam-deploy-${config.STACK_NAME}-${config.AWS_REGION}`;
  console.log(`Checking deployment bucket: ${deployBucket}...`);

  try {
    execSync(`aws s3 ls s3://${deployBucket} --region ${config.AWS_REGION}`, { stdio: 'ignore' });
    console.log('✓ Deployment bucket exists\n');
  } catch {
    console.log('Creating deployment bucket...');
    execCommand(`aws s3 mb s3://${deployBucket} --region ${config.AWS_REGION}`, PROJECT_ROOT);
    console.log('');
  }

  // Build backend
  console.log('Building backend...\n');
  execCommand('npm run build');

  // Build with SAM
  console.log('\nBuilding with SAM...\n');
  execCommand('sam build');

  // Deploy to AWS (pass parameters via CLI)
  console.log('\nDeploying to AWS...\n');
  const productionOrigins = config.PRODUCTION_ORIGINS || '';
  const paramOverrides = `IncludeDevOrigins="${config.INCLUDE_DEV_ORIGINS}" ProductionOrigins="${productionOrigins}" LambdaMemory=${config.LAMBDA_MEMORY} LambdaTimeout=${config.LAMBDA_TIMEOUT}`;
  execCommand(`sam deploy --parameter-overrides ${paramOverrides}`);

  // Get stack outputs
  console.log('\nRetrieving stack outputs...\n');
  const outputs = getStackOutputs(config.STACK_NAME, config.AWS_REGION);

  const apiUrlOutput = outputs.find(o => o.OutputKey === 'VocabularySyncApiUrl');
  const tableNameOutput = outputs.find(o => o.OutputKey === 'UserProgressTableName');

  if (!apiUrlOutput) {
    console.error('✗ VocabularySyncApiUrl not found in stack outputs');
    process.exit(1);
  }

  const apiUrl = apiUrlOutput.OutputValue;
  const tableName = tableNameOutput ? tableNameOutput.OutputValue : '(unknown)';

  // Update .env file
  updateEnvFile(apiUrl);

  console.log('==========================================');
  console.log('Deployment Complete!');
  console.log('==========================================\n');
  console.log('Stack Resources:');
  console.log(`  API URL:    ${apiUrl}`);
  console.log(`  Table Name: ${tableName}\n`);
  console.log('Next steps:');
  console.log('1. Your .env file has been updated with EXPO_PUBLIC_SYNC_API_URL');
  console.log('2. Run "npm start" to start your app\n');
}

// Run deployment
deploy().catch(error => {
  console.error('\n✗ Deployment failed:', error.message);
  rl.close();
  process.exit(1);
});
